const CATEGORY_CLICK = 'CATEGORY_CLICK';
const PRICE_ASC = 'PRICE_ASC';
const PRICE_DESC = 'PRICE_DESC';
const STORE_GAMES = 'STORE_GAMES';
const NAME_FILTER = 'NAME_FILTER';
const STORE_CATEGORIES = 'STORE_CATEGORIES';
const SELECT_CATEGORY = 'SELECT_CATEGORY';
const PRICE = 'PRICE';

export const ListingTypes = {
  CATEGORY_CLICK,
  PRICE_ASC,
  PRICE_DESC,
  STORE_GAMES,
  NAME_FILTER,
  STORE_CATEGORIES,
  SELECT_CATEGORY,
  PRICE
};
